<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>ML </b></center>

<center><b><h1>Lab - 7</b></center>    
<pre>    

# Decision Tree Classifier

In [96]:
from sklearn.datasets import load_iris 

# Import iris data ser using sklearn

In [99]:
data = load_iris()

In [101]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

# Importing the libraries

In [104]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import tree

# Divide the data into input and output

In [107]:
X = data['data']
y = data['target']
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Splitting the dataset into the Training set and Test set

In [110]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3
)

In [112]:
X_test

array([[5.1, 3.8, 1.9, 0.4],
       [6.5, 2.8, 4.6, 1.5],
       [6.4, 2.8, 5.6, 2.1],
       [6.4, 3.2, 4.5, 1.5],
       [4.4, 3. , 1.3, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [6. , 2.2, 4. , 1. ],
       [6.9, 3.1, 5.1, 2.3],
       [5.5, 2.4, 3.7, 1. ],
       [5. , 3.3, 1.4, 0.2],
       [6.8, 2.8, 4.8, 1.4],
       [7.7, 2.8, 6.7, 2. ],
       [6.9, 3.1, 5.4, 2.1],
       [5.8, 2.7, 4.1, 1. ],
       [7.2, 3.2, 6. , 1.8],
       [7.2, 3. , 5.8, 1.6],
       [6.4, 3.2, 5.3, 2.3],
       [4.9, 3.1, 1.5, 0.1],
       [6.2, 2.9, 4.3, 1.3],
       [4.9, 3. , 1.4, 0.2],
       [6.9, 3.1, 4.9, 1.5],
       [5.1, 3.8, 1.5, 0.3],
       [6.3, 2.5, 5. , 1.9],
       [5.8, 2.7, 3.9, 1.2],
       [5.4, 3.9, 1.3, 0.4],
       [6.7, 3.3, 5.7, 2.1],
       [6. , 2.9, 4.5, 1.5],
       [6.3, 2.7, 4.9, 1.8],
       [5.7, 3.8, 1.7, 0.3],
       [6.5, 3. , 5.2, 2. ],
       [5. , 3.4, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 2.3, 4.4, 1.3],
       [5.5, 2

# Fitting DecisionTreeClassifier   on dataset

In [115]:
model = DecisionTreeClassifier()

In [117]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

# Display Decision Tree

In [120]:
%matplotlib inline

In [122]:
tree.plot_tree(model)

[Text(0.3333333333333333, 0.9166666666666666, 'x[3] <= 0.8\ngini = 0.666\nsamples = 105\nvalue = [36, 36, 33]'),
 Text(0.2222222222222222, 0.75, 'gini = 0.0\nsamples = 36\nvalue = [36, 0, 0]'),
 Text(0.2777777777777778, 0.8333333333333333, 'True  '),
 Text(0.4444444444444444, 0.75, 'x[2] <= 4.75\ngini = 0.499\nsamples = 69\nvalue = [0, 36, 33]'),
 Text(0.38888888888888884, 0.8333333333333333, '  False'),
 Text(0.3333333333333333, 0.5833333333333334, 'gini = 0.0\nsamples = 32\nvalue = [0, 32, 0]'),
 Text(0.5555555555555556, 0.5833333333333334, 'x[3] <= 1.75\ngini = 0.193\nsamples = 37\nvalue = [0, 4, 33]'),
 Text(0.3333333333333333, 0.4166666666666667, 'x[3] <= 1.55\ngini = 0.5\nsamples = 6\nvalue = [0, 3, 3]'),
 Text(0.2222222222222222, 0.25, 'x[2] <= 4.95\ngini = 0.375\nsamples = 4\nvalue = [0, 1, 3]'),
 Text(0.1111111111111111, 0.08333333333333333, 'gini = 0.0\nsamples = 1\nvalue = [0, 1, 0]'),
 Text(0.3333333333333333, 0.08333333333333333, 'gini = 0.0\nsamples = 3\nvalue = [0, 0, 3]

In [130]:
plt.show()

# Predict the x_test 

In [132]:
model.predict(X_test)

array([0, 1, 2, 1, 0, 0, 1, 2, 1, 0, 1, 2, 2, 1, 2, 1, 2, 0, 1, 0, 1, 0,
       2, 1, 0, 2, 1, 2, 0, 2, 0, 2, 1, 1, 1, 2, 0, 1, 1, 0, 0, 2, 1, 2,
       0])

In [134]:
y_test

array([0, 1, 2, 1, 0, 0, 1, 2, 1, 0, 1, 2, 2, 1, 2, 2, 2, 0, 1, 0, 1, 0,
       2, 1, 0, 2, 1, 2, 0, 2, 0, 2, 1, 1, 1, 2, 0, 2, 1, 0, 0, 2, 2, 2,
       0])

In [136]:
model.score(X_train,y_train)

1.0

In [138]:
model.score(X_test,y_test)

0.9333333333333333

# Import diabetes.csv dataset 

In [141]:
df = pd.read_csv("diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,Diabetic
1,1,85,66,29,0,26.6,0.351,31,Non Diabetic
2,8,183,64,0,0,23.3,0.672,32,Diabetic
3,1,89,66,23,94,28.1,0.167,21,Non Diabetic
4,0,137,40,35,168,43.1,2.288,33,Diabetic
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,Non Diabetic
764,2,122,70,27,0,36.8,0.340,27,Non Diabetic
765,5,121,72,23,112,26.2,0.245,30,Non Diabetic
766,1,126,60,0,0,30.1,0.349,47,Diabetic


# Check the distribution of the target

In [144]:
print(df['Outcome'].value_counts())

Outcome
Non Diabetic    500
Diabetic        268
Name: count, dtype: int64


# Replace zeros with NaN for specific columns

In [147]:
columns_to_replace = ["Pregnancies","Glucose","BloodPressure","SkinThickness","Insulin","BMI"]
df[columns_to_replace] = df[columns_to_replace].replace(0,np.nan)

# Check for missing values

In [150]:
print(df.isnull().sum())

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64


# Fill missing values with median

In [153]:
for col in columns_to_replace:
    df[col] = df[col].fillna(df[col].median())

In [155]:
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64


# Visualize Distributions

In [158]:
import seaborn as sns
sns.pairplot(df,hue='Outcome')

# Convert Targer data into interger code

In [166]:
df['Outcome'] = df['Outcome'].map({"Diabetic":1,"Non-diabetic":0})

In [168]:
sns.heatmap(df.corr(),anno = True ,cmap='coolwarm')
plt.show()

AttributeError: QuadMesh.set() got an unexpected keyword argument 'anno'

# Divide the data into input and output

In [ ]:
X = df.iloc[::,:-1:]

In [ ]:
y = df['Outcome']

# Splitting the dataset into the Training set and Test set

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3
)

# Create Model

In [162]:
model = DecisionTreeClassifier()

# Fitting DecisionTreeClassifier   on dataset

In [164]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

# Display Decision Tree

# Predict the x_test 

# Display Training Accuracy

# Display Test Accuracy

# Confusion Matrix

# Save Model State

In [ ]:
import pickle

# Load Model from Disk